name: SootReports-Waterfall
main: dev.codeerror.sootreports.SootReports
version: 1.1
api-version: 1.17
description: A custom player/bug reports and suggestions plugin for the Waterfall proxy. Programmed for SootMC.
author: CodeError
website: https://www.codeerror.dev/
load: STARTUP
commands:
  report:
    description: Report command for SootReports.
    permission: sootreports.command.report
    permission-message: §8[§1SootReports§8] §cYou do not have the appropriate permissions to perform this command.
    usage: /report <player> <reason>
  bug:
    description: Bug command for SootReports.
    permission: sootreports.command.bug
    permission-message: §8[§1SootReports§8] §cYou do not have the appropriate permissions to perform this command.
    usage: /bug <bug>
  suggest:
    description: Suggest command for SootReports.
    permission: sootreports.command.suggest
    permission-message: §8[§1SootReports§8] §cYou do not have the appropriate permissions to perform this command.
    usage: /suggest <suggestion>
permissions:
  sootreports.*:
    description: Grants access to all permission nodes in SootReports.
    default: op
    children:
      sootreports.command.report: true
      sootreports.command.bug: true
      sootreports.command.suggest: true
      sootreports.notify.report: true
  sootreports.command.*:
    description: Grants access to report, bug and suggest commands.
    default: op
    children:
      sootreports.command.report: true
      sootreports.command.bug: true
      sootreports.command.suggest: true
  sootreports.notify.*:
    description: Grants access to report, bug and suggest in-game notifications.
    default: op
    children:
      sootreports.notify.report: true
  sootreports.command.report:
    description: Grants access to report command.
    default: op
  sootreports.command.bug:
    description: Grants access to bug command.
    default: op
  sootreports.command.suggest:
    description: Grants access to suggest command.
    default: op
  sootreports.notify.report:
    description: Grants access to report in-game notifications.
    default: op
